version: '3'
services:
  api:
    build: ./api
    depends_on:
      - db
    volumes:
      - ./api/:/usr/api/
    ports:
      - 3000:3000
    env_file: .env
    environment:
      SERVER_PORT: 3000

  scraper:
    build: ./scraper
    depends_on:
      - api
    volumes:
      - ./scraper/src/:/usr/src/
    env_file: .env
    environment:
      SERVER_PORT: 3000

  db:
    build:
      context: ./dev
      dockerfile: Dockerfile-MongoDB
    volumes:
      - ./dev/db/:/data/db/
    ports:
      - 27017:27017

  api_prod:
    build: ./api
    ports:
      - 80:80
    env_file: .env
    environment:
      SERVER_PORT: 80
    restart: on-failure

  scraper_prod:
    build: ./scraper
    depends_on:
      - api_prod
    env_file: .env
    environment:
      SERVER_PORT: 80
    restart: on-failure
