version: '3'
services:
  api:
    build: ./api
    depends_on:
      - db
    volumes:
      - ./api/:/usr/api/

  scraper:
    build: ./scraper
    depends_on:
      - api
    volumes:
      - ./scraper/src/:/usr/src/

  db:
    build:
      context: ./dev
      dockerfile: Dockerfile-MongoDB
    volumes:
      - ./dev/db/:/data/db/
