version: '3'
services:
  api:
    build: ./api
    depends_on:
      - db
    volumes:
      - ./api/:/usr/api/
    ports:
      - 3000:3000
    environment:
      DB_ADDRESS: 'mongodb://db:27017/dev'
      SECURITY_KEY: 'topsecret'

  scraper:
    build: ./scraper
    depends_on:
      - api
    volumes:
      - ./scraper/src/:/usr/src/

  db:
    build:
      context: ./dev
      dockerfile: Dockerfile-MongoDB
    volumes:
      - ./dev/db/:/data/db/
    ports:
      - 27017:27017
